### ISSUE TITLE
V12 - Character Sheet Missing After Update

### ISSUE THREAD

**Issue by allizar212** [AutarchLLC/foundryvtt-acks-core#30] opened 2024-07-20 21:47 UTC
**Describe the bug**
After attempting to update to test V12, character sheet formatting is gone.

**To Reproduce**
1. Download the zip of the initiative branch
2. Extract and replace the files from SRC into the data/system/acks folder of Foundry, or alternatively delete the contents of the v11 acks folder and extract the files from SRC into it
3. Launch foundry and select a character sheet of a "character" or "monster"

**Expected behavior**
The standard formatted character sheet from v11 is expected

**Screenshots**
![Capture](https://github.com/user-attachments/assets/786a2536-6233-4ac7-9aa6-afec4518b12a)

**Comment by LeRatierBretonnien** [comment] 2024-08-01 19:51
Unable to reproduce. Are you sure to download and replace the whole content of the system ?

**Comment by LeRatierBretonnien** [comment] 2024-08-02 06:45
You can try this new initiative branch, with all latest updates also : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/download/12.0.2/system.zip

**Comment by LeRatierBretonnien** [comment] 2024-08-03 13:00
Oops, 
New release, with all latest fixes : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/download/12.0.11/system.json

**Comment by ArcanistWill** [comment] 2024-08-24 23:11
@allizar212 I don't have a good answer for you currently for your issue because I had the same issue. I am not completely sure that this method you used will work. I have had problems if I am locally running a server, and I try to just download new code and overwrite the contents of a working directory. It's as if there is something missing between the final build and the installed game system, when trying to update it that way.

@LeRatierBretonnien is there an easy way to take a running Foundry server (I assume running locally) and paste in the latest URL to our build, and get that to load into the game system?

**Comment by LeRatierBretonnien** [comment] 2024-08-25 07:27
No I do not know an "easy" way. The simplest way is to copy/paste the manifest link of a test release into the relevant field (1)  in Foundry, and then press (2) : 
![image](https://github.com/user-attachments/assets/00140d10-ea46-4453-9bbe-b1566c5f9a4d)

But in your case, I think you downloaded a broken version (ie my fault). So I think the issue can be closed.

**Comment by ArcanistWill** [comment] 2024-12-24 16:17
We think this is resolved. Closing.

**Closed by ArcanistWill** 2024-12-24 16:17 UTC
