### ISSUE TITLE
V12 - equipment Activation/De-activation

### ISSUE THREAD

**Issue by dasBarkman** [AutarchLLC/foundryvtt-acks-core#28] opened 2024-07-01 18:54 UTC
**Describe the bug**
When clicking on the button to equip armour, it doesn't equip.

**To Reproduce**
1.Create a character actor
2. Open the armour item folder (after importing from compedium)
3. Drag armour item to actor - inventory tab
4. click on the torso to equip the item
5. Icon doesn't light up to register that the armour is worn, no changes to AC on actor first page. 

**Expected behavior**
When equipped, armour should change the AC of the actor, and light up the icon indicating it is equipped.

**Screenshots**
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/165521079/2d66db80-37d5-448a-9d7e-5e5630c09400)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version Current

**Additional context**

**Comment by ArcanistWill** [comment] 2024-07-06 03:03
Here is additional feedback from another user:

1. Has anyone else had issues with equipping items from the armor slot since updating foundry to V12? I have to manually adjust AC as a tweak. Items that were equipped can not be unequipped either
2. To add to this, this also occurs with weapons and not being able to roll them. It only works if it was on a character sheet prior to updating to v12.

**Comment by LeRatierBretonnien** [comment] 2024-08-01 19:51
I suggest to close this issue

**Comment by LeRatierBretonnien** [comment] 2024-08-02 19:08
Fix available in latest release : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/tag/12.0.2

**Comment by LeRatierBretonnien** [comment] 2024-08-03 13:01
Oops, 
New release, with all latest fixes : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/download/12.0.11/system.json

**Comment by ArcanistWill** [comment] 2024-08-11 20:35
I've tested and confirmed the fix. Closing.

**Closed by ArcanistWill** 2024-08-11 20:35 UTC
