### ISSUE TITLE
V12 Initiative issue

### ISSUE THREAD

**Issue by dasBarkman** [AutarchLLC/foundryvtt-acks-core#27] opened 2024-06-30 05:19 UTC
When adding actors to combat, things progress normally.   Roll initiative for all actors in the combat.
Click next turn, it appears to restart the round, and not progress through the actors in initiative order..

**To Reproduce**
1. Add Actors to the encounter (highlight and right click on one, then click on sword and shield icon)
2. Go to encounter tab
3. Click 'roll all'
4. Right click on first person in list - set active, if not active already.
5. Click Next Turn on bottom of tab.

**Expected behavior**
On expected behaviour it should advance the initiative order and go to the next person in order.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version Latest current version

**Comment by LeRatierBretonnien** [comment] 2024-07-07 07:26
Unable to reproduce. The proper way is : 

1. Add Actors to the encounter (highlight and right click on one, then click on sword and shield icon)
2. Go to encounter tab
3. **Begin combat**
4. Resolve the surprise dialog
5. Then initiative is rolled
6. Loop thru combattants with "Next Combattant"

**Comment by LeRatierBretonnien** [comment] 2024-07-07 08:01
But in order to avoid this misunderstanding, I will add a check to produce a message when the combat is not started.
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/1085008/4a83c22b-ed37-4f0b-8464-779b934081c0)

**Comment by LeRatierBretonnien** [comment] 2024-08-01 19:50
I suggest to close this ticket.

**Comment by LeRatierBretonnien** [comment] 2024-08-02 19:08
Warning messages available in latest release here : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/tag/12.0.2

**Comment by LeRatierBretonnien** [comment] 2024-08-04 06:02
Use latest release with all fixes : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/download/12.0.11/system.json

**Comment by ArcanistWill** [comment] 2024-08-24 22:08
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed. I can't reproduce the same issue. Looks ok to me.

**Closed by ArcanistWill** 2024-08-24 22:08 UTC
